### ISSUE TITLE
MlflowLogger: Invalid metric name: 'val/AR@100'. Names may only contain alphanumerics, underscores (_), dashes (-), periods (.), spaces ( ), and slashes (/)

### ISSUE THREAD

**Issue by ihoholko** [open-mmlab/mmdetection#10258]
Current mlflow logger doesn't support metrics logging from `CocoMetric`'s `proposal`:

**Metrics**
```yaml
val_evaluator:
  ann_file: ${data_root}/equifish_annotations/valdataset_toy.json
  type: CocoMetric
  metric: ['bbox', 'proposal']
  iou_thrs: [0.2]
``` 

**Logger**
```yaml
# @package modules.MLflowVisBackend

type: MLflowVisBackend
save_dir: temp_dir #${paths.output_dir} #(str): The root directory to save the files produced by the backend.
exp_name: ${name}             #(str, optional): The experiment name. Default to None.
run_name: ${run_name}         #(str, optional): The run name. Default to None.
tags: null                 #(dict, optional): The tags to be added to the experiment. Default to None.
params: null                  #(dict, optional): The params to be added to the experiment. Default to None.
tracking_uri: http://${oc.env:MLFLOW_USERNAME}:${oc.env:MLFLOW_PASSWORD}@${oc.env:MLFLOW_HOST}
artifact_suffix: ['.json', '.log', '.py', 'yaml']     # (Tuple[str] or str, optional): The artifact suffix. Default to ('.json', '.log', '.py', 'yaml').
```

Are there some flags to fix this behaviour? 

**Env**
```yaml
mmcv                     2.0.0
mmdet                    3.0.0                /home/oem/Projects/aimosaic-roi/3rd/mmdetection
mmengine                 0.7.3
smmap                    5.0.0
```
